// generated by parseCompaniesCsv.js
// DO NOT EDIT MANUALLY. ONLY GENERATE USING 'npm run parse-companies'
/**** GEN:S id="companies-csv" */
export const companies = JSON.parse(`[
  {
    "companyName": "Chandler Studios",
    "focuses": "3D printing, manufacturing and design",
    "positionTypes": [
      "Interns",
      "Full-time employees",
      "Part-time employees",
      "Contract workers",
      "Freelancers",
      "Volunteers"
    ],
    "website": "https://www.chandlerla.com/",
    "virtualTimes": "",
    "inPersonTimes": "",
    "logoUrlCheckString": "Option 2"
  }
]`);
/**** GEN:E id="companies-csv" */

// edit manually
export const pastCompanies: string[] = Array.from(new Set([
  "900lbs",
  "A Bunch Of Short Guys",
  "AEM Creations",
  "Aggieland Outfitters",
  "Bluepoint Games",
  "BonusXP",
  "Booz Allen Hamilton, Inc.",
  "C.C. Creations",
  "Cinevva",
  "Click Here Labs - TRG",
  "Cloud Imperium Games",
  "Credera",
  "Deloitte",
  "Digital Seat Media",
  "DreamWorks Animation",
  "Electronic Arts",
  "Framestore",
  "Game Worlds",
  "Gearbox Software",
  "IMG Studio",
  "Jacobs Architects",
  "Mighty Coconut",
  "Pixar",
  "Powerhouse Animation",
  "ReelFX",
  "Six Foot Games",
  "Texas Film Commission",
  "Texas Moving Picture Alliance (TXMPA)",
  "The Third Floor, Inc.",
  "TRG",
  "Walt Disney",
  "Viasat",
]));
pastCompanies.sort((a, b) => a.toLowerCase() <= b.toLowerCase() ? -1 : 1);
